CapstoneBookApp/CapstoneBookApp/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
namespace CapstoneBookApp.Models
{
    public class Book
    {
        [Key]
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int Pages { get; set; }
        public double Price { get; set; }
        public DateTime Published { get; set; }
        public ICollection<Copy> Copies { get; set; }
    }
    //Seth1
}

CapstoneBookApp/CapstoneBookApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapstoneBookApp.DataAccessLayer;
using CapstoneBookApp.Models;

namespace CapstoneBookApp.Controllers
{
    public class BooksController : Controller
    {
        private BookAppContext db = new BookAppContext();

        // GET: Books
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookID,Title,Author,Pages,Price,Published")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookID,Title,Author,Pages,Price,Published")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapstoneBookApp/CapstoneBookApp/Controllers/CopiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapstoneBookApp.DataAccessLayer;
using CapstoneBookApp.Models;

namespace CapstoneBookApp.Controllers
{
    public class CopiesController : Controller
    {
        private BookAppContext db = new BookAppContext();

        // GET: Copies
        public ActionResult Index()
        {
            var copies = db.Copies.Include(c => c.Book).Include(c => c.Library);
            return View(copies.ToList());
        }

        // GET: Copies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copy copy = db.Copies.Find(id);
            if (copy == null)
            {
                return HttpNotFound();
            }
            return View(copy);
        }

        // GET: Copies/Create
        public ActionResult Create()
        {
            ViewBag.BookID = new SelectList(db.Books, "BookID", "Title");
            ViewBag.LibraryID = new SelectList(db.Libraries, "LibraryID", "LibraryName");
            return View();
        }

        // POST: Copies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CopyID,CheckedOut,BookFormat,BookID,LibraryID")] Copy copy)
        {
            if (ModelState.IsValid)
            {
                db.Copies.Add(copy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BookID = new SelectList(db.Books, "BookID", "Title", copy.BookID);
            ViewBag.LibraryID = new SelectList(db.Libraries, "LibraryID", "LibraryName", copy.LibraryID);
            return View(copy);
        }

        // GET: Copies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copy copy = db.Copies.Find(id);
            if (copy == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookID = new SelectList(db.Books, "BookID", "Title", copy.BookID);
            ViewBag.LibraryID = new SelectList(db.Libraries, "LibraryID", "LibraryName", copy.LibraryID);
            return View(copy);
        }

        // POST: Copies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CopyID,CheckedOut,BookFormat,BookID,LibraryID")] Copy copy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(copy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookID = new SelectList(db.Books, "BookID", "Title", copy.BookID);
            ViewBag.LibraryID = new SelectList(db.Libraries, "LibraryID", "LibraryName", copy.LibraryID);
            return View(copy);
        }

        // GET: Copies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copy copy = db.Copies.Find(id);
            if (copy == null)
            {
                return HttpNotFound();
            }
            return View(copy);
        }

        // POST: Copies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Copy copy = db.Copies.Find(id);
            db.Copies.Remove(copy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapstoneBookApp/CapstoneBookApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapstoneBookApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Books()
        {
            ViewBag.Message = "Books page.";

            return View();
        }

        public ActionResult Copies()
        {
            ViewBag.Message = "Copies page.";

            return View();
        }

        public ActionResult Libraries()
        {
            ViewBag.Message = "Libraries page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CapstoneBookApp/CapstoneBookApp/Controllers/LibrariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapstoneBookApp.DataAccessLayer;
using CapstoneBookApp.Models;

namespace CapstoneBookApp.Controllers
{
    public class LibrariesController : Controller
    {
        private BookAppContext db = new BookAppContext();

        // GET: Libraries
        public ActionResult Index()
        {
            return View(db.Libraries.ToList());
        }

        // GET: Libraries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Library library = db.Libraries.Find(id);
            if (library == null)
            {
                return HttpNotFound();
            }
            return View(library);
        }

        // GET: Libraries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Libraries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LibraryID,LibraryName,Manager")] Library library)
        {
            if (ModelState.IsValid)
            {
                db.Libraries.Add(library);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(library);
        }

        // GET: Libraries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Library library = db.Libraries.Find(id);
            if (library == null)
            {
                return HttpNotFound();
            }
            return View(library);
        }

        // POST: Libraries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LibraryID,LibraryName,Manager")] Library library)
        {
            if (ModelState.IsValid)
            {
                db.Entry(library).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(library);
        }

        // GET: Libraries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Library library = db.Libraries.Find(id);
            if (library == null)
            {
                return HttpNotFound();
            }
            return View(library);
        }

        // POST: Libraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Library library = db.Libraries.Find(id);
            db.Libraries.Remove(library);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapstoneBookApp/CapstoneBookApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CapstoneBookApp/CapstoneBookApp/Views/Home/Books.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../styles.css">
    <link href="https://fonts.googleapis.com/css?family=Vollkorn:400,400i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <title>Bookworld</title>
    @Styles.Render("~/Content/css")
</head>
<body>

    @{ 
        Html.RenderPartial("_Navbar");
    }

    <div class="main">

        <p class="main-title">books</p>
        <div class="btn add-new">add a book</div>

        <div class="list">

            <div class="list-header">
                <h3 class="list-header__item book-title">Title</h3>
                <h3 class="list-header__item book-author">Author</h3>
                <h3 class="list-header__item book-pages">Pages</h3>
                <h3 class="list-header__item book-date">Date</h3>
                <h3 class="list-header__item book-price">Price</h3>
            </div>

            <div class="item-list">

                <div class="list-row">
                    <p class="row-item book-title">The Lord of the Rings</p>
                    <p class="row-item book-author">J.R.R. Tolkien</p>
                    <p class="row-item book-pages">1138</p>
                    <p class="row-item book-date">July 24, 1954</p>
                    <p class="row-item book-price">$0.00</p>
                    <span class="edit-btn">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>
                

                <div class="list-row">
                    <p class="row-item book-title">To Kill a Mockingbird</p>
                    <p class="row-item book-author">Harper Lee</p>
                    <p class="row-item book-pages">296</p>
                    <p class="row-item book-date">July 11, 1960</p>
                    <p class="row-item book-price">$0.00</p>
                    <span class="edit-btn">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>

                <div class="list-row">
                    <p class="row-item book-title">The Bell Jar</p>
                    <p class="row-item book-author">Sylvia Plath</p>
                    <p class="row-item book-pages">244</p>
                    <p class="row-item book-date">January 14, 1963</p>
                    <p class="row-item book-price">$0.00</p>
                    <span class="edit-btn">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>

            </div>

        </div>

    </div>


</body>
</html>

CapstoneBookApp/CapstoneBookApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CapstoneBookApp/CapstoneBookApp/Views/Home/Copies.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../styles.css">
    <link href="https://fonts.googleapis.com/css?family=Vollkorn:400,400i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <title>Bookworld</title>
    @Styles.Render("~/Content/css")

</head>
<body>

    @{
        Html.RenderPartial("_Navbar");
    }

    <div class="main">

        <p class="main-title">copies</p>
        <button class="btn add-new">add a copy</button>

        <div class="list">

            <div class="list-header">
                <h3 class="list-header__item checked-out">Checked Out</h3>
                <h3 class="list-header__item checkout-date">Book Format</h3>
            </div>

            <div class="item-list">

                <div class="list-row copies-row">
                    <p class="row-item checked-out">yes</p>
                    <p class="row-item checkout-date">Paperback</p>
                    <span class="edit-btn copies-edit">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>

                <div class="list-row copies-row">
                    <p class="row-item checked-out">no</p>
                    <p class="row-item checkout-date">Ebook</p>
                    <span class="edit-btn copies-edit">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>

            </div>

        </div>

    </div>


</body>
</html>

CapstoneBookApp/CapstoneBookApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="intro">
    <p class="prequel">welcome to</p>
    <h1 class="title">Bookworld</h1>
    <p class="sequel">where your book, copy, and library dreams come true</p>
</div>

<div class="options-section">

    <p class="prompt">pick your poison...</p>

    <div class="options">
        <a href="@(Url.Action("Index", "Books"))">
            <div class="box">
                <p>books</p>
            </div>
        </a>
        <a href="@(Url.Action("Index", "Copies"))">
            <div class="box">
                <p>copies</p>
            </div>
        </a>
        <a href="@(Url.Action("Index", "Libraries"))">
            <div class="box">
                <p>libraries</p>
            </div>
        </a>
    </div>

</div>

CapstoneBookApp/CapstoneBookApp/Views/Home/Libraries.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../styles.css">
    <link href="https://fonts.googleapis.com/css?family=Vollkorn:400,400i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <title>Bookworld</title>
    @Styles.Render("~/Content/css")
</head>
<body>

    @{
        Html.RenderPartial("_Navbar");
    }

    <div class="main">

        <p class="main-title">libraries</p>
        <button class="btn add-new">add a library</button>

        <div class="list">

            <div class="list-header">
                <h3 class="list-header__item lib-name">Library Name</h3>
                <h3 class="list-header__item lib-manager">Manager</h3>
            </div>

            <div class="item-list">

                <div class="list-row libraries-row">
                    <p class="row-item lib-name">The Library</p>
                    <p class="row-item lib-manager">Dr. Library</p>
                    <span class="edit-btn libraries-edit">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>

                <div class="list-row libraries-row">
                    <p class="row-item lib-name">The Library II</p>
                    <p class="row-item lib-manager">Dr. Library</p>
                    <span class="edit-btn libraries-edit">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>

                <div class="list-row libraries-row">
                    <p class="row-item lib-name">The Library III</p>
                    <p class="row-item lib-manager">Dr. Library</p>
                    <span class="edit-btn libraries-edit">
                        <i class="fas fa-edit"></i>
                        <i class="fas fa-trash"></i>
                    </span>
                </div>
            </div>

        </div>

    </div>


</body>
</html>